# Generated by Django 6.0.1 on 2026-06-23 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Are YUM Studio', max_length=200)),
                ('subheading', models.TextField()),
                ('story_title', models.CharField(default='Our Story', max_length=100)),
                ('story_description', models.TextField()),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('team_members_count', models.PositiveIntegerField(default=0)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'db_table': 'about',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_logos',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('project_image', models.ImageField(upload_to='projects/')),
                ('website', models.URLField(blank=True, null=True)),
                ('project_summary', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('youtube', 'YouTube'), ('behance', 'Behance'), ('dribbble', 'Dribbble')], max_length=50, unique=True)),
                ('icon', models.CharField(default='Unknown', max_length=50)),
                ('url', models.URLField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_no', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'social_media',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('client_title', models.CharField(max_length=50)),
                ('client_image', models.ImageField(upload_to='testimonials/')),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating out of 5 (1–5)')),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order_no', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'values',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='services/covers/')),
                ('pitch', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devapp.service')),
            ],
            options={
                'db_table': 'inbox',
            },
        ),
        migrations.CreateModel(
            name='ServiceBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='devapp.service')),
            ],
            options={
                'db_table': 'service_badges',
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='devapp.service')),
            ],
            options={
                'db_table': 'service_deliverables',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('src', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='devapp.service')),
            ],
            options={
                'db_table': 'service_gallery',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveIntegerField()),
                ('revisions', models.CharField(max_length=100)),
                ('highlight', models.BooleanField(default=False)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='devapp.service')),
            ],
            options={
                'db_table': 'service_pricing_tiers',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('pricing_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='devapp.servicepricingtier')),
            ],
            options={
                'db_table': 'service_pricing_features',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='devapp.service')),
            ],
            options={
                'db_table': 'service_processes',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_title', models.CharField(max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=200, null=True)),
                ('client_image', models.URLField()),
                ('testimonial', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating out of 5 (1–5)')),
                ('review_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='devapp.service')),
            ],
            options={
                'db_table': 'service_reviews',
            },
        ),
        migrations.CreateModel(
            name='ServiceTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='devapp.service')),
            ],
            options={
                'db_table': 'service_tools',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='devapp.service')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='devapp.service')),
            ],
            options={
                'db_table': 'service_related',
                'unique_together': {('service', 'related_service')},
            },
        ),
    ]
