# Generated by Django 6.0.1 on 2026-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
