# Generated by Django 6.0.1 on 2026-04-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0002_project_project_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='We Are YUM Studio', max_length=200)),
                ('subheading', models.TextField()),
                ('story_title', models.CharField(default='Our Story', max_length=100)),
                ('story_description', models.TextField()),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('happy_clients', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('team_members_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
